name: tess-audio-utils
channels:
  - anaconda
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - panoptes_client
    - Requests
    - strauss @ git+https://github.com/james-trayford/strauss.git
    - python-dotenv
